### ISSUE TITLE
🛑 Earthquake EEW WebSocket Program is down

### ISSUE THREAD

**Issue by naknjp** [Narikakun-Network/status-page#33]
In [`914cf7b`](https://github.com/Narikakun-Network/status-page/commit/914cf7b0de400188b1ee42e3d048c0b461e2293a
), Earthquake EEW WebSocket Program ($EARTHQUAKE_EEW_WS) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by narikakun** [comment]
サービス終了
